export const MET_VALUES: Record<string, number> = {
  "Walking (slow, 2 mph)": 2.5,
  "Walking (moderate, 3 mph)": 3.5,
  "Walking (brisk, 3.5 mph)": 3.8,
  "Walking (fast, 4 mph)": 5.0,
  "Running (5 mph)": 8.3,
  "Running (6 mph)": 9.8,
  "Running (7 mph)": 11.0,
  "Running (8 mph)": 11.8,
  "Running (9 mph)": 12.8,
  "Running (10 mph)": 14.5,
  "Cycling (leisure, <10 mph)": 4.0,
  "Cycling (moderate, 10-12 mph)": 8.0,
  "Cycling (vigorous, 14-16 mph)": 10.0,
  "Swimming (leisure)": 6.0,
  "Swimming (vigorous)": 9.8,
  "Jump rope": 11.8,
  Yoga: 3.0,
  Pilates: 3.5,
  "Stretching / flexibility": 2.5,
  "Weight training (light)": 3.5,
  "Weight training (vigorous)": 6.0,
  "Aerobics (low impact)": 5.0,
  "Aerobics (high impact)": 7.3,
  "Elliptical (moderate)": 5.0,
  "Rowing machine (moderate)": 7.0,
  "Stair climbing": 8.8,
  "Hiking (general)": 5.3,
  "Rock climbing": 8.0,
  "Basketball (game)": 8.0,
  "Basketball (shooting hoops)": 4.5,
  "Soccer (general)": 7.0,
  "Tennis (singles)": 8.0,
  "Tennis (doubles)": 5.0,
  Badminton: 5.5,
  Volleyball: 4.0,
  "Dancing (general)": 5.0,
  Zumba: 6.5,
  Kickboxing: 9.5,
  "Boxing (sparring)": 9.0,
  "Martial arts": 10.0,
  Skateboarding: 5.0,
  Rollerblading: 7.5,
  "Skiing (downhill)": 6.0,
  "Cross-country skiing": 9.0,
  Snowboarding: 5.3,
  Surfing: 3.0,
  Kayaking: 5.0,
  "Golf (walking)": 4.3,
  "Golf (riding cart)": 2.5,
  Gardening: 3.5,
  "Lawn mowing (push)": 5.0,
  "House cleaning": 3.0,
  "Carrying groceries (upstairs)": 5.0,
  "Moving furniture": 5.8,
  "Shoveling snow": 6.0,
  "Playing with kids (active)": 4.0,
  "Dog walking": 3.0,
  "Wheelchair sports": 6.5,
  "Water aerobics": 5.5,
  "Tai chi": 3.5,
  Frisbee: 3.5,
};

export const MET_ACTIVITY_NAMES: readonly string[] = Object.keys(MET_VALUES);

// MET * 3.5 * weightKg / 200 * durationMin (ACSM formula)
export function computeCaloriesBurned(
  activityType: string,
  durationMin: number,
  weightKg: number,
): number {
  const met = MET_VALUES[activityType] ?? 4.0;
  return Math.round((met * 3.5 * weightKg * durationMin) / 200);
}
